<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/GMailConnector/SendMessage_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/GMailConnector/SendMessage_REQUEST" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:nssrcmpr="http://oracle-integration.cloud/soap/IntegratedSourceFlightSchedules/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns2="http://xmlns.oracle.com/cloud/generic/rest/fault/GMailConnector/SendMessage_REQUEST" exclude-result-prefixes=" xp20 oraext xsi oracle-xsl-mapper xsl fn xsd soapenc http soap mime nssrcmpr ora ignore01" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:nsmpr0="file://metadata-catalog.json" xmlns:xml="http://www.w3.org/XML/1998/namespace">
	<oracle-xsl-mapper:schema xml:id="id_2">
		<!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
		<oracle-xsl-mapper:mapSources xml:id="id_3">
			<oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
				<oracle-xsl-mapper:schema location="../../application_88/outbound_228/resourcegroup_40/MissingPersonReport_REQUEST.wsdl" xml:id="id_5"/>
				<oracle-xsl-mapper:rootElement name="MissingPersonReport" namespace="http://oracle-integration.cloud/soap/IntegratedSourceFlightSchedules/" xml:id="id_6"/>
			</oracle-xsl-mapper:source>
		</oracle-xsl-mapper:mapSources>
		<oracle-xsl-mapper:mapTargets xml:id="id_7">
			<oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
				<oracle-xsl-mapper:schema location="../../application_81/inbound_822/resourcegroup_619/SendMessage_REQUEST.wsdl" xml:id="id_9"/>
				<oracle-xsl-mapper:rootElement name="sendMsg" namespace="http://xmlns.oracle.com/cloud/adapter/GMailConnector/SendMessage_REQUEST/types" xml:id="id_10"/>
			</oracle-xsl-mapper:target>
		</oracle-xsl-mapper:mapTargets>
		<!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
	</oracle-xsl-mapper:schema>
	<!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
	<xsl:template match="/" xml:id="id_11">
		<xsl:variable name="email">
			<xsl:value-of select="'concat('To: ', concat(/nssrcmpr:MissingPersonReport/nssrcmpr:mailSettings/nssrcmpr:to)" xml:id="id_18"/>
			<xsl:text xml:id="id_19">&#xa;</xsl:text>
			<xsl:value-of select="concat('From: ', concat(/nssrcmpr:MissingPersonReport/nssrcmpr:mailSettings/nssrcmpr:from)" xml:id="id_20"/>
			<xsl:text xml:id="id_21">&#xa;</xsl:text>
			<xsl:value-of select="'Subject: Missing Person Report'" xml:id="id_22"/>
			<xsl:text xml:id="id_23">&#xa;</xsl:text>
			<xsl:value-of select="'Content-Type: text/plain; charset=utf-8'" xml:id="id_24"/>
			<xsl:text xml:id="id_25">&#xa;</xsl:text>
			<xsl:value-of select="'MIME-Version: 1.0'" xml:id="id_26"/>
			<xsl:text xml:id="id_27">&#xa;</xsl:text>
			<xsl:text xml:id="id_28">&#xa;</xsl:text>
			<xsl:value-of select="'New missing person report:'" xml:id="id_29"/>
			<xsl:text xml:id="id_30">&#xa;</xsl:text>
			<xsl:text xml:id="id_31">&#xa;</xsl:text>
			<xsl:value-of xml:id="id_32"
					  select="concat(/nssrcmpr:MissingPersonReport/nssrcmpr:missingPerson/nssrcmpr:title, ' ', /nssrcmpr:MissingPersonReport/nssrcmpr:missingPerson/nssrcmpr:initials, ' (', /nssrcmpr:MissingPersonReport/nssrcmpr:missingPerson/nssrcmpr:firstName, ') ', /nssrcmpr:MissingPersonReport/nssrcmpr:missingPerson/nssrcmpr:lastName, ' is late for flight #', /nssrcmpr:MissingPersonReport/nssrcmpr:ident)"/>
			<xsl:text xml:id="id_33">&#xa;</xsl:text>
			<xsl:value-of xml:id="id_34"
					  select='concat ("Luggage Tag #", /nssrcmpr:MissingPersonReport/nssrcmpr:missingPerson/nssrcmpr:luggageTag )'/>
		</xsl:variable>
		<nstrgmpr:sendMsg xml:id="id_12">
			<nstrgmpr:Messages.definitions.requestPayLoadForSendMsg xml:id="id_13">
				<nsmpr0:raw xml:id="id_14">
					<xsl:value-of select="$email" xml:id="id_15"/>
				</nsmpr0:raw>
			</nstrgmpr:Messages.definitions.requestPayLoadForSendMsg>
			<nstrgmpr:QueryParameters xml:id="id_16">
				<nsmpr0:uploadType xml:id="id_17">media</nsmpr0:uploadType>
			</nstrgmpr:QueryParameters>
		</nstrgmpr:sendMsg>
	</xsl:template>
</xsl:stylesheet>
